FROM node:18-alpine AS base
EXPOSE 80

WORKDIR /src
COPY ./Src/Website/package.json .
COPY ./Src/Website/package-lock.json .

RUN npm ci

COPY ./Src/Website/ .
RUN npm run build

ENTRYPOINT npm run start:prod -- --port 80 --host 0.0.0.0
