using System.Text;
using CSharpier.SyntaxPrinter;
using System.Text.Json;

namespace CSharpier;

public class CodeFormatter
{
    public static LanguageVersion LanguageVersion = LanguageVersion.Preview;

    public static string Format(string code, CodeFormatterOptions? options = null)
    {
        return FormatAsync(code, options).Result;
    }

    public static async Task<string> FormatAsync(
        string code,
        CodeFormatterOptions? options = null,
        CancellationToken cancellationToken = default
    )
    {
        options ??= new();

        var result = await FormatAsync(
            code,
            new PrinterOptions { Width = options.Width },
            cancellationToken
        );
        return result.Code;
    }

    public static string Format(SyntaxTree syntaxTree, CodeFormatterOptions? options = null)
    {
        return FormatAsync(syntaxTree, options).Result;
    }

    public static async Task<string> FormatAsync(
        SyntaxTree syntaxTree,
        CodeFormatterOptions? options = null,
        CancellationToken cancellationToken = default
    )
    {
        options ??= new();

        var result = await FormatAsync(
            syntaxTree,
            new PrinterOptions { Width = options.Width },
            cancellationToken
        );
        return result.Code;
    }

    internal static CodeFormatterResult Format(string code, PrinterOptions printerOptions)
    {
        return FormatAsync(code, printerOptions, CancellationToken.None).Result;
    }

    internal static Task<CodeFormatterResult> FormatAsync(
        string code,
        PrinterOptions printerOptions,
        CancellationToken cancellationToken
    )
    {
        // if a user supplied symbolSets, then we should start with the first one
        var initialSymbolSet = printerOptions.PreprocessorSymbolSets is { Count: > 0 }
            ? printerOptions.PreprocessorSymbolSets.First()
            : Array.Empty<string>();

        return FormatAsync(
            ParseText(code, initialSymbolSet, cancellationToken),
            printerOptions,
            cancellationToken
        );
    }

    private static async Task<CodeFormatterResult> FormatAsync(
        SyntaxTree syntaxTree,
        PrinterOptions printerOptions,
        CancellationToken cancellationToken
    )
    {
        var syntaxNode = await syntaxTree.GetRootAsync(cancellationToken);
        if (syntaxNode is not CompilationUnitSyntax rootNode)
        {
            throw new Exception(
                "Root was not CompilationUnitSyntax, it was " + syntaxNode.GetType()
            );
        }

        if (GeneratedCodeUtilities.BeginsWithAutoGeneratedComment(rootNode))
        {
            return new CodeFormatterResult { Code = syntaxTree.ToString() };
        }

        bool TryGetCompilationFailure(out CodeFormatterResult compilationResult)
        {
            var diagnostics = syntaxTree!
                .GetDiagnostics(cancellationToken)
                .Where(o => o.Severity == DiagnosticSeverity.Error && o.Id != "CS1029")
                .ToList();
            if (diagnostics.Any())
            {
                compilationResult = new CodeFormatterResult
                {
                    Code = syntaxTree.ToString(),
                    Errors = diagnostics,
                    AST = printerOptions.IncludeAST ? PrintAST(rootNode) : string.Empty
                };

                return true;
            }

            compilationResult = CodeFormatterResult.Null;
            return false;
        }

        if (TryGetCompilationFailure(out var result))
        {
            return result;
        }

        try
        {
            if (printerOptions.PreprocessorSymbolSets is { Count: > 0 })
            {
                PreprocessorSymbols.StopCollecting();
                PreprocessorSymbols.SetSymbolSets(
                    // we already formatted with the first set above
                    printerOptions.PreprocessorSymbolSets.Skip(1).ToList()
                );
            }
            else
            {
                PreprocessorSymbols.Reset();
            }

            var lineEnding = GetLineEnding(syntaxTree.ToString(), printerOptions);
            var document = Node.Print(rootNode, new FormattingContext { LineEnding = lineEnding });
            var formattedCode = DocPrinter.DocPrinter.Print(document, printerOptions, lineEnding);

            PreprocessorSymbols.StopCollecting();
            foreach (var symbolSet in PreprocessorSymbols.GetSymbolSets())
            {
                syntaxTree = ParseText(formattedCode, symbolSet, cancellationToken);

                if (TryGetCompilationFailure(out result))
                {
                    return result;
                }

                document = Node.Print(
                    await syntaxTree.GetRootAsync(cancellationToken),
                    new FormattingContext()
                );
                formattedCode = DocPrinter.DocPrinter.Print(document, printerOptions, lineEnding);
            }

            return new CodeFormatterResult
            {
                Code = formattedCode,
                DocTree = printerOptions.IncludeDocTree
                    ? DocSerializer.Serialize(document)
                    : string.Empty,
                AST = printerOptions.IncludeAST ? PrintAST(rootNode) : string.Empty
            };
        }
        catch (InTooDeepException)
        {
            return new CodeFormatterResult
            {
                FailureMessage = "We can't handle this deep of recursion yet."
            };
        }
    }

    private static SyntaxTree ParseText(
        string codeToFormat,
        string[] preprocessorSymbols,
        CancellationToken cancellationToken
    )
    {
        return CSharpSyntaxTree.ParseText(
            codeToFormat,
            new CSharpParseOptions(
                LanguageVersion,
                DocumentationMode.Diagnose,
                preprocessorSymbols: preprocessorSymbols
            ),
            cancellationToken: cancellationToken
        );
    }

    internal static string GetLineEnding(string code, PrinterOptions printerOptions)
    {
        if (printerOptions.EndOfLine != EndOfLine.Auto)
        {
            return printerOptions.EndOfLine == EndOfLine.CRLF ? "\r\n" : "\n";
        }

        var lineIndex = code.IndexOf('\n');
        if (lineIndex <= 0)
        {
            return "\n";
        }
        if (code[lineIndex - 1] == '\r')
        {
            return "\r\n";
        }

        return "\n";
    }

    private static string PrintAST(CompilationUnitSyntax rootNode)
    {
        var stringBuilder = new StringBuilder();
        SyntaxNodeJsonWriter.WriteCompilationUnitSyntax(stringBuilder, rootNode);
        return JsonSerializer.Serialize(
            JsonSerializer.Deserialize<object>(stringBuilder.ToString()),
            new JsonSerializerOptions { WriteIndented = false }
        );
    }
}

internal class CodeFormatterResult
{
    public string Code { get; init; } = string.Empty;
    public string DocTree { get; init; } = string.Empty;
    public string AST { get; init; } = string.Empty;
    public IEnumerable<Diagnostic> Errors { get; init; } = Enumerable.Empty<Diagnostic>();

    public string FailureMessage { get; init; } = string.Empty;

    public static readonly CodeFormatterResult Null = new();
}
