using Microsoft.Extensions.Logging;
using System.CommandLine;

namespace CSharpier.Cli;

internal class CommandLineOptions
{
    public string[] DirectoryOrFilePaths { get; init; } = [];
    public bool Check { get; init; }
    public LogFormat LogFormat { get; init; }
    public bool Fast { get; init; }
    public bool SkipWrite { get; init; }
    public bool WriteStdout { get; init; }
    public bool NoCache { get; init; }
    public bool NoMSBuildCheck { get; init; }
    public bool CompilationErrorsAsWarnings { get; init; }
    public bool IncludeGenerated { get; init; }
    public string? StandardInFileContents { get; init; }
    public string? ConfigPath { get; init; }
    public string[] OriginalDirectoryOrFilePaths { get; init; } = [];

    internal delegate Task<int> Handler(
        string[] directoryOrFile,
        bool check,
        LogFormat logFormat,
        bool fast,
        bool skipWrite,
        bool writeStdout,
        bool pipeMultipleFiles,
        bool server,
        int? serverPort,
        bool noCache,
        bool noMSBuildCheck,
        bool includeGenerated,
        bool compilationErrorsAsWarnings,
        string config,
        LogLevel logLevel,
        CancellationToken cancellationToken
    );

    public static RootCommand Create()
    {
        var rootCommand = new RootCommand
        {
            new Argument<string[]>("directoryOrFile")
            {
                Arity = ArgumentArity.ZeroOrMore,
                Description =
                    "One or more paths to a directory containing C# files to format or a C# file to format. It may be ommited when piping data via stdin.",
            }.LegalFilePathsOnly(),
            new Option(["--check"], "Check that files are formatted. Will not write any changes."),
            new Option<string>(
                ["--loglevel"],
                () => LogLevel.Information.ToString(),
                "Specify the log level - Debug, Information (default), Warning, Error, None"
            ),
            new Option<LogFormat>(
                ["--log-format"],
                () => LogFormat.Console,
                """
                Log output format
                    Console - Formats messages in a human readable way for console
                              interaction.
                    MsBuild - Formats messages in standard error/warning format for MSBuild.
                """
            ),
            new Option(
                ["--no-cache"],
                "Bypass the cache to determine if a file needs to be formatted."
            ),
            new Option(
                ["--no-msbuild-check"],
                "Bypass the check to determine if a csproj files references a different version of CSharpier.MsBuild."
            ),
            new Option(
                ["--include-generated"],
                "Include files generated by the SDK and files that begin with <autogenerated /> comments"
            ),
            new Option(
                ["--fast"],
                "Skip comparing syntax tree of formatted file to original file to validate changes."
            ),
            new Option(
                ["--skip-write"],
                "Skip writing changes. Generally used for testing to ensure csharpier doesn't throw any errors or cause syntax tree validation failures."
            ),
            new Option(["--write-stdout"], "Write the results of formatting any files to stdout."),
            new Option(
                ["--pipe-multiple-files"],
                "Keep csharpier running so that multiples files can be piped to it via stdin."
            ),
            new Option(
                ["--server"],
                "Run CSharpier as a server so that multiple files may be formatted."
            ),
            new Option<int?>(
                ["--server-port"],
                "Specify the port that CSharpier should start on. Defaults to a random unused port."
            ),
            new Option<string>(["--config-path"], "Path to the CSharpier configuration file"),
            new Option(
                ["--compilation-errors-as-warnings"],
                "Treat compilation errors from files as warnings instead of errors."
            ),
        };

        rootCommand.AddValidator(cmd =>
        {
            if (!Console.IsInputRedirected && cmd.Children.Contains("--pipe-multiple-files"))
            {
                return "--pipe-multiple-files may only be used if you pipe stdin to CSharpier";
            }
            if (
                !Console.IsInputRedirected
                && !cmd.Children.Contains("directoryOrFile")
                && !cmd.Children.Contains("--server")
            )
            {
                return "directoryOrFile is required when not piping stdin to CSharpier";
            }

            return null;
        });

        return rootCommand;
    }
}
