using CSharpier.Tests.TestFileTests;
using NUnit.Framework;

namespace CSharpier.Tests.TestFiles
{
    public class AutoGeneratedFiles : BaseTest
    {
        [Test]
        public void AutoGenerated()
        {
            this.RunTest("AutoGeneratedFiles", "AutoGenerated");
        }
        [Test]
        public void AutoDashGenerated()
        {
            this.RunTest("AutoGeneratedFiles", "AutoDashGenerated");
        }
    }
}
