name: Publish CSharpier
on:
  push:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - uses: actions/checkout@v2
      - run: dotnet test Src/CSharpier.Tests/CSharpier.Tests.csproj
  publish-nuget:
    runs-on: ubuntu-latest
    name: publish nuget
    needs: test
    env:
      VERSION_FILE_PATH: CSharpier.Build.props
      TAG_FORMAT: "*"
      NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    steps:
      - uses: actions/checkout@v2
      - name: Publish CSharpier.Core library on version change
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: Src/CSharpier/CSharpier.csproj
      - name: Publish CSharpie dotnet tool on version change
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: Src/CSharpier.Cli/CSharpier.Cli.csproj
      - name: Publish CSharpier.MsBuild library on version change
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: Src/CSharpier.MsBuild/CSharpier.MsBuild.csproj