name: Publish CSharpier
on:
  push:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - uses: actions/checkout@v2
      - run: dotnet test Src/CSharpier.Tests/CSharpier.Tests.csproj
  publish-nuget:
    runs-on: ubuntu-latest
    name: publish nuget
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: publish csharpier on version change
        id: publish_csharpier_nuget
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: Src/CSharpier/CSharpier.csproj
          VERSION_FILE_PATH: CSharpier.Build.props
          TAG_FORMAT: "*"
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
      - name: publish csharpier.cli on version change
        id: publish_csharpier_cli_nuget
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: Src/CSharpier.CLI/CSharpier.CLI.csproj
          VERSION_FILE_PATH: CSharpier.Build.props
          TAG_FORMAT: "*"
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
      - name: publish csharpier.msbuild on version change
        id: publish_csharpier_msbuild_nuget
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: Src/CSharpier.MsBuild/CSharpier.MsBuild.csproj
          VERSION_FILE_PATH: CSharpier.Build.props
          TAG_FORMAT: "*"
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}