name: Publish
on:
  push:
    branches: [ 1.0.0 ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v3
      - uses: gittools/actions/gitversion/setup@v3.1.1
        with:
          versionSpec: '6.0.x'
      - uses: gittools/actions/gitversion/execute@v3.1.1
      - run: |
          dotnet pack Src/CSharpier.Cli/CSharpier.Cli.csproj -c Release /p:Version=${{env.VERSION}} /p:InformationalVersion=${{env.VERSION}} -o dist
          dotnet nuget push ./dist/CSharpier.${{env.VERSION}}.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json
          git tag ${{env.VERSION}}
          git push origin ${{env.VERSION}}
        env:
          VERSION: ${{env.branchName}}-alpha${{env.commitsSinceVersionSource}}
